package com.dewijones92.totum.common

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class SubtitleTrackTest {

    private val url = HttpUrl.of("https://example.com/en.vtt")

    @Test
    fun `each format carries the mime type the player needs`() {
        assertEquals("text/vtt", SubtitleFormat.VTT.mimeType)
        assertEquals("application/x-subrip", SubtitleFormat.SRT.mimeType)
        assertEquals("application/ttml+xml", SubtitleFormat.TTML.mimeType)
    }

    @Test
    fun `recognises the renderable extensions, however they are cased`() {
        assertEquals(SubtitleFormat.VTT, SubtitleFormat.fromExtension("vtt"))
        assertEquals(SubtitleFormat.VTT, SubtitleFormat.fromExtension("WebVTT"))
        assertEquals(SubtitleFormat.SRT, SubtitleFormat.fromExtension("SRT"))
        assertEquals(SubtitleFormat.TTML, SubtitleFormat.fromExtension("dfxp"))
    }

    /**
     * YouTube's own caption formats. A track we can't decode must not become a menu entry
     * that silently shows nothing, so these have to resolve to null rather than a guess.
     */
    @Test
    fun `refuses formats the player cannot decode`() {
        listOf("srv1", "srv2", "srv3", "json3", "", "ttml2").forEach {
            assertNull(it, SubtitleFormat.fromExtension(it))
        }
    }

    @Test(expected = IllegalArgumentException::class)
    fun `a blank language code is not representable`() {
        SubtitleTrack("  ", "English", url, autoGenerated = false, format = SubtitleFormat.VTT)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `a blank label is not representable`() {
        SubtitleTrack("en", " ", url, autoGenerated = false, format = SubtitleFormat.VTT)
    }

    @Test
    fun `a valid track keeps what it was given`() {
        val track = SubtitleTrack("en-GB", "English (UK)", url, autoGenerated = true, format = SubtitleFormat.VTT)

        assertEquals("en-GB", track.languageCode)
        assertEquals("English (UK)", track.label)
        assertEquals(url, track.url)
    }
}
