package com.dewijones92.totum.innertube.player

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Reading a video's identity and its chapters out of a `/player` response.
 *
 * This is what makes InnerTube able to resolve a video on its own rather than only supplement
 * yt-dlp: streams alone were never enough to play something.
 *
 * Chapters are parsed from the description because yt-dlp parses them from exactly the same
 * text. Duplicating that is what stops a faster path silently costing a feature.
 */
class PlayerDetailsTest {

    @Test
    fun `reads a video's identity, including the channel it belongs to`() {
        val body = """
            {"playabilityStatus":{"status":"OK"},
             "streamingData":{"formats":[{"itag":18,"mimeType":"video/mp4","height":360,
               "url":"https://r1.example.com/a"}]},
             "videoDetails":{"videoId":"aqz-KE-bpKQ","title":"Big Buck Bunny","author":"Blender",
               "channelId":"UCSMOQeBJ2RAnuFungnQOxLg","lengthSeconds":"635","isLiveContent":false,
               "shortDescription":"A short film.",
               "thumbnail":{"thumbnails":[{"url":"https://i.example.com/small.jpg"},
                                          {"url":"https://i.example.com/big.jpg"}]}}}
        """.trimIndent()

        val details = (PlayerResponseParser.parse(body) as PlayerResult.Success).details!!

        assertEquals("Big Buck Bunny", details.title)
        assertEquals("Blender", details.author)
        assertEquals("UCSMOQeBJ2RAnuFungnQOxLg", details.channelId)
        assertEquals(635L, details.lengthSeconds)
        // Largest wins: they arrive smallest-first.
        assertEquals("https://i.example.com/big.jpg", details.thumbnailUrl?.value)
    }

    /**
     * YouTube serves `fmt=srv3` — its own XML, which nothing in Media3 renders. The same
     * endpoint serves WebVTT for the asking.
     */
    @Test
    fun `caption tracks are asked for as WebVTT, and auto-generated ones say so`() {
        val body = """
            {"playabilityStatus":{"status":"OK"},
             "streamingData":{"formats":[{"itag":18,"mimeType":"video/mp4","height":360,
               "url":"https://r1.example.com/a"}]},
             "captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[
               {"baseUrl":"https://www.youtube.com/api/timedtext?v=x&lang=en&fmt=srv3",
                "name":{"runs":[{"text":"English"}]},"vssId":".en","languageCode":"en"},
               {"baseUrl":"https://www.youtube.com/api/timedtext?v=x&lang=de&fmt=srv3",
                "name":{"runs":[{"text":"German"}]},"vssId":"a.de","languageCode":"de"}]}}}
        """.trimIndent()

        val subs = (PlayerResponseParser.parse(body) as PlayerResult.Success).subtitles

        assertEquals(listOf("English", "German (auto-generated)"), subs.map { it.label })
        assertEquals(listOf(false, true), subs.map { it.autoGenerated })
        assertTrue("srv3 renders nowhere", subs.all { "fmt=vtt" in it.url.value })
    }

    @Test
    fun `chapters are parsed out of the description`() {
        val chapters = chaptersFromDescription(
            """
            Some blurb about the video.

            0:00 Intro
            1:23 - The middle bit
            1:02:03 The long tail
            """.trimIndent(),
        )

        assertEquals(listOf(0L, 83L, 3723L), chapters.map { it.first })
        assertEquals(listOf("Intro", "The middle bit", "The long tail"), chapters.map { it.second })
    }

    /**
     * A description is free text. Without the must-start-at-zero rule any prose mentioning a
     * time — "we talk at 4:30 about…" — becomes a bogus chapter list, and YouTube's own rule
     * for a chaptered video is that the first mark is at zero.
     */
    @Test
    fun `timestamps in prose are not a chapter list`() {
        assertTrue(chaptersFromDescription("We get into it at 4:30 properly").isEmpty())
        assertTrue(chaptersFromDescription("1:23 Second thing\n2:00 Third thing").isEmpty())
        assertTrue(chaptersFromDescription(null).isEmpty())
    }

    @Test
    fun `a timestamp with no title is not a chapter`() {
        assertTrue(chaptersFromDescription("0:00\n1:00").isEmpty())
    }
}
