package com.dewijones92.totum.common

/**
 * A subtitle/caption track that can actually be rendered.
 *
 * Lives here, beside [HttpUrl] and [Page], because both sides need it: the extraction
 * engine produces them and the domain/playback layers consume them — and podcasts have
 * transcripts too (`podcast:transcript` in RSS), so this is the seam that will serve both
 * pillars rather than a video-only type that later needs a twin.
 */
public data class SubtitleTrack(
    /** BCP-47-ish code as the source reports it: "en", "en-GB", "es-419". */
    public val languageCode: String,
    /** What to show in a menu — "English", or "English (auto-generated)". */
    public val label: String,
    public val url: HttpUrl,
    /**
     * True for machine transcription. Worth surfacing rather than hiding: auto captions
     * are useful but wrong often enough that you want to know which you're reading.
     */
    public val autoGenerated: Boolean,
    public val format: SubtitleFormat,
) {
    init {
        require(languageCode.isNotBlank()) { "languageCode must not be blank" }
        require(label.isNotBlank()) { "label must not be blank" }
    }

    /**
     * The language without its region or variant: "en" for all of "en", "en-GB" and
     * YouTube's "en-orig". What a menu should collapse on — three flavours of English is a
     * list, not a choice.
     */
    public val baseLanguage: String get() = languageCode.substringBefore('-').lowercase()
}

/**
 * Subtitle formats the player can decode, with the MIME type it needs to be told.
 *
 * Deliberately a closed set: a track in a format we can't render is worse than no track,
 * because it appears in the menu and then silently shows nothing. Sources offer plenty we
 * can't use (YouTube's `srv1`/`srv2`/`srv3`/`json3`), and [fromExtension] returns null for
 * those so they're dropped at the boundary.
 */
public enum class SubtitleFormat(public val mimeType: String) {
    VTT("text/vtt"),
    SRT("application/x-subrip"),
    TTML("application/ttml+xml"),
    ;

    public companion object {
        /** Null when the extension isn't something we can render. */
        public fun fromExtension(extension: String): SubtitleFormat? = when (extension.lowercase()) {
            "vtt", "webvtt" -> VTT
            "srt" -> SRT
            "ttml", "dfxp" -> TTML
            else -> null
        }
    }
}
